#!/bin/bash
n=$(who | wc -l)
while [ $n != 0 ]
do
echo $(who | head -n $n |tail -n 1 |awk '{print $1}') \
$(date -d@$(( $(date -ud now +%s) - $(date -ud "$(who | head -n $n |tail -n 1 |awk '{print $3,$4}')" +%s) )) +'%H:%M')
let " n = $n - 1 ";
done
